import type { LexiconEntry, RegexRule } from './types.js';

export const REGEX_RULES: RegexRule[] = [
  {
    id: 'A.emphasis_opener',
    category: 'A',
    re: /(?:^|[\s,.])(핵심은|중요한 것은|중요한 건|주목할 점은|주목해야 할 점은|한 가지 분명한 건|사실은|문제는)/g,
    severity: 'high',
    message: '강조 도입어. AI가 도입부를 무겁게 내리는 전형 패턴',
    suggestion: '곧장 본문으로. 도입어 없이 단언',
  },
  {
    id: 'A.contrast_rhetoric',
    category: 'A',
    re: /(?:단순한|단순히|단지|그저|그냥)\s+[가-힣A-Za-z0-9 ]{1,20}(?:이|가)\s*아니라/g,
    severity: 'high',
    message: '"단순한 X가 아니라 Y" 대조 수사. Y가 추상명사면 의미 운반 거의 없음',
    suggestion: 'Y만 단언으로 풀어쓰기',
  },
  {
    id: 'A.summative_closer',
    category: 'A',
    re: /(?:^|[\s,.])(결론적으로|결국 핵심은|한마디로|정리하자면|요약하자면|요약하면)/g,
    severity: 'high',
    message: '수렴 마무리. 본문이 이미 결론으로 향하고 있을 때 군더더기',
    suggestion: '삭제. 다음 문장이 결론임을 직접 말함',
  },
  {
    id: 'A.precision_claim',
    category: 'A',
    re: /(정확히 말하면|엄밀히 말해|사실 더 정확히는)/g,
    severity: 'medium',
    message: '정정 수사. 앞 문장 자체가 부정확하다는 신호',
    suggestion: '한 번에 정확하게 말하기',
  },
  {
    id: 'A.meta_response',
    category: 'A',
    re: /(좋은 질문(?:입니다|이에요)|흥미로운 지점(?:입니다|이에요)|맞습니다, 그리고)/g,
    severity: 'medium',
    message: '메타 발화. 응답 자체에 대한 코멘트라 본문이 아님',
    suggestion: '삭제',
  },
  {
    id: 'A.meta_announce',
    category: 'A',
    re: /(살펴보겠습니다|알아보겠습니다|설명드리겠습니다|설명해드리겠습니다|정리해보겠습니다|소개해드리겠습니다|알려드리겠습니다|다뤄보겠습니다|짚어보겠습니다)/g,
    severity: 'medium',
    message: '행동 예고. AI가 할 것을 미리 선언하는 클리셰',
    suggestion: '선언 없이 곧장 내용으로',
  },

  {
    id: 'B.colon_title',
    category: 'B',
    re: /다음과 같(?:은|이|습니다|아요)/g,
    severity: 'medium',
    message: '"다음과 같이" 콜론 제목 양식. AI 출력 형식의 상징',
    suggestion: '제목 없이 바로 내용. 또는 한 문장으로 풀어쓰기',
  },
  {
    id: 'B.tilde_range',
    category: 'B',
    re: /(?<=[가-힣0-9])\s*~\s*(?=[가-힣0-9])/g,
    severity: 'low',
    message: '물결표 범위. 한국어 리듬과 안 맞고 일부 렌더러에서 취소선',
    suggestion: '"에서" 또는 하이픈으로',
    fix: '에서 ',
  },
  {
    id: 'B.em_dash',
    category: 'B',
    re: /—/g,
    severity: 'low',
    message: '엠대시. 영어 문장 부호라 한국어에 이질',
    suggestion: '쉼표·괄호·마침표로',
  },

  {
    id: 'C.passive_chain',
    category: 'C',
    re: /(되어지|되어진|어지고 있|어지게 된)/g,
    severity: 'high',
    message: '이중피동. 한국어가 가장 싫어하는 번역체',
    suggestion: '단순 피동(되다) 또는 능동',
  },
  {
    id: 'C.by_passive',
    // "에 의해" 뒤 가까이에 피동 동사(되·받·당하·지)가 따라올 때만 잡는다.
    // im-not-ai by_passive 방식. "법에 의해 보호받는다"는 잡고, 정당한 행위자 표시는 덜 건드린다.
    category: 'C',
    re: /에\s*의(?:해|하여)\s+\S{0,12}?(?:되|받|당하|지)(?:다|었|어|ㄴ다|는다|는|ㄹ|을|던|음)/g,
    severity: 'high',
    message: '"~에 의해 …되다" 수동문. 영어 by의 직역',
    suggestion: '능동형 "X가 ~한다"로',
  },
  {
    id: 'C.have_have',
    category: 'C',
    re: /(?:를|을) 가지고 있/g,
    severity: 'high',
    message: '"~을 가지고 있다". 영어 have의 직역',
    suggestion: '"~이 있다"',
  },

  {
    id: 'D1.locating',
    category: 'D1',
    re: /위치하고 있/g,
    severity: 'medium',
    message: '"위치하고 있다"는 "있다"의 부풀림',
    suggestion: '"있다"',
    fix: '있',
  },
  {
    id: 'D1.about',
    category: 'D1',
    // "에 대하여"를 "에 대해"보다 먼저 둬야 alternation이 긴 쪽을 먼저 먹는다.
    // 뒤 공백 강제를 없애 문말 "…에 대한."도 잡는다. 한 번은 자연스러우니 2회+에서만.
    re: /에 대하여|에 대한|에 대해서?/g,
    severity: 'medium',
    message: '"~에 대한/대해". 영어 about·on의 직역. 반복되면 무거워짐',
    suggestion: '을·를로 처리하거나 생략',
    minRepeat: 2,
  },
  {
    id: 'D1.via',
    category: 'D1',
    re: /(?:을|를) 통해/g,
    severity: 'low',
    message: '"~을 통해". through의 직역. 남용 시 어색',
    suggestion: '"~로" 또는 "~에서"',
    minRepeat: 2,
  },
  {
    id: 'D1.from',
    category: 'D1',
    re: /로부터 /g,
    severity: 'medium',
    message: '"~로부터". from의 직역',
    suggestion: '"~에서" 또는 "~에게"',
  },
  {
    id: 'D1.in_doing',
    category: 'D1',
    re: /함에 있어/g,
    severity: 'high',
    message: '"함에 있어서". 일본·영어 직역',
    suggestion: '"~할 때"',
    fix: '할 때',
  },
  {
    id: 'D1.despite',
    category: 'D1',
    re: /(?:에도|임에도|음에도) 불구하고/g,
    severity: 'medium',
    message: '"에도 불구하고". despite의 직역. 남용 시 문장이 무거워짐',
    suggestion: '"하지만"·"그래도"·역접 "는"으로 짧게',
  },

  {
    id: 'E.eui_chain',
    category: 'E',
    re: /[가-힣]+의\s+[가-힣]+의/g,
    severity: 'medium',
    message: '"~의" 연속. 영어 of-of 직역',
    suggestion: '풀어쓰기. 한 번 끊어서',
  },
  {
    id: 'E.eui_density',
    category: 'E',
    re: /[가-힣]{1,6}의\s+[가-힣]{1,8}(?:과|와|을|를|이|가|에|에서|으로|로)\s+[가-힣]{1,6}의/g,
    severity: 'medium',
    message: '"~의" 밀도. 한 구절에 ~의 두 번. 풀어쓸 자리',
    suggestion: '동사로 풀거나 끊어쓰기',
  },
  {
    id: 'E.suffix_jeok',
    category: 'E',
    re: /[가-힣]적(?:인|으로|인 것)/g,
    severity: 'low',
    message: '~적 (일본식 접미사)',
    suggestion: '풀어쓸 수 있으면 풀기',
    minRepeat: 3,
  },
  {
    id: 'E.suffix_seong',
    category: 'E',
    re: /[가-힣]성(?:을|이|은|의)/g,
    severity: 'low',
    message: '~성 (추상명사화)',
    suggestion: '동사로 풀거나 구체로 내려가기',
    minRepeat: 3,
  },
  {
    id: 'E.intent_eomi',
    category: 'E',
    re: /해보겠(?:어요|습니다)/g,
    severity: 'medium',
    message: '의도형 어미. 행동형이 자연스러움',
    suggestion: '"할게요" 또는 "합니다"',
  },

  {
    id: 'F.abstract_verbalization',
    category: 'F',
    re: /(재정의|재설정|재정립|정립|구축|확장|강화|극대화|최적화|활성화|구체화|정교화|고도화|추진|검토|고려|수립|모색|도입|발굴|발휘|향상|증진|확보|운영)(?:에|을|를|이|가|하|해)/g,
    severity: 'medium',
    message: '추상명사 동작화. "재정의·구축·정립·추진·검토·수립" 같은 한자어가 의미를 가림',
    suggestion: '구체 동사로 내려가기 (무엇을 어떻게)',
  },
  {
    id: 'F.hedge_softener',
    category: 'F',
    re: /(?:라고 할 수 있|인 것 같|인 것으로 보|일 수도)/g,
    severity: 'low',
    message: '완충 표현. 단언이 흐려짐',
    suggestion: '단언 ("~이다", "~한다")',
  },
  {
    id: 'F.formal_verb_chain',
    category: 'F',
    re: /(이루어지|만들어지|행해지|구성되어|수행되)/g,
    severity: 'medium',
    message: '형식 동사. 의미 운반이 약한 한자어 동사 + 피동',
    suggestion: '강한 고유어 동사로 (잇다·짜다·풀다·짚다)',
  },
  {
    id: 'F.abstract_arrival',
    category: 'F',
    re: /(?:의미|메시지|뜻|결론|효과|영향|핵심)(?:가|이)\s*도달/g,
    severity: 'medium',
    message: '"의미가 도달한다" 류. 영어 reach/arrive의 추상 직역',
    suggestion: '"잘 전달되다" / "통하다"',
  },
  {
    id: 'F.abstract_arrival_2',
    category: 'F',
    re: /도달(?:하지|하는|한다는|하지 않)/g,
    severity: 'low',
    message: '"도달"이 추상 의미로 쓰이면 영어 직역 의심',
    suggestion: '구체 동작이면 "닿다·이르다", 의미 전달이면 "전달되다·통하다"',
  },
  {
    id: 'F.degree_adverb',
    category: 'F',
    re: /(?:매우|정말|진짜|굉장히|대단히|극히|너무나|무척)/g,
    severity: 'low',
    message: '정도부사 반복. "매우·정말·굉장히"는 강조를 더하는 듯하나 의미를 안 더함',
    suggestion: '삭제하거나 구체 수치·사례로',
    minRepeat: 2,
  },
  {
    id: 'F.formal_noun',
    category: 'F',
    re: /것(?:이다|입니다|이에요)/g,
    severity: 'low',
    message: '"~것이다" 종결 반복. 형식명사가 핵심 동사를 가림',
    suggestion: '"~다"로 직결',
    minRepeat: 2,
  },
  {
    id: 'E.double_particle',
    category: 'E',
    re: /(?:에서의|에로의|으로의|에의|으로부터의|로부터의)/g,
    severity: 'medium',
    message: '이중 조사. "에서의·으로의"는 일본어·영어 번역체의 격 결합',
    suggestion: '조사 하나로 풀기 ("폭격에 의해 끊어진" → "폭격으로 끊어진")',
  },
  {
    id: 'B.emoji',
    category: 'B',
    re: /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2B00}-\u{2BFF}\u{2190}-\u{21FF}]/gu,
    severity: 'low',
    message: '이모지 남발. 에세이·리포트에서 AI 출력의 상징',
    suggestion: '본문에서 제거. 정말 필요한 1개만',
    minRepeat: 3,
  },
];

export const D2_LEXICON: LexiconEntry[] = [
  { word: '합성기', natural: '신디사이저', contextSafe: ['음성', '단백질', '화학', '효소', 'DNA'], severity: 'medium' },
  { word: '처리기', natural: '프로세서', contextSafe: ['이벤트', '문자열', '예외', '자연어'], severity: 'low' },
  { word: '응답기', natural: '리스폰더', contextSafe: ['자동', '비상'], severity: 'low' },
  { word: '저장기', natural: '저장 장치', contextSafe: ['혈액', '곡물'], severity: 'medium' },
  { word: '연산기', natural: '계산기', contextSafe: ['병렬', '벡터'], severity: 'low' },
  { word: '가공기', natural: '프로세서·머신', contextSafe: ['식품', '금속', '목재', '플라스틱'], severity: 'low' },
  { word: '발생기', natural: '제너레이터', contextSafe: ['신호', '전기', '증기', '난수'], severity: 'low' },
  { word: '송신기', natural: '트랜스미터', contextSafe: ['무선', '라디오', 'RF'], severity: 'low' },
  { word: '수신기', natural: '리시버', contextSafe: ['라디오', 'GPS', '무선'], severity: 'low' },
  { word: '변환기', natural: '컨버터', contextSafe: ['전압', '신호', '디지털', '아날로그'], severity: 'low' },
  { word: '생성기', natural: '제너레이터', contextSafe: ['난수', '신호', '전기', 'OTP', '토큰', '보고서'], severity: 'medium' },
  { word: '분류기', natural: '분류 모델', contextSafe: ['이메일', '문서', '텍스트', '스팸', '베이즈'], severity: 'low' },
  { word: '인식기', natural: '인식 모델', contextSafe: ['음성', '얼굴', '필기', '문자', '패턴', '이미지'], severity: 'low' },
];
